/*
 * ODK Runner
 * Copyright (C) 2024 Damien Goutte-Gattat
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 * 3. The name of the author may not be used to endorse or promote
 *    products derived from this software without specific prior written
 *    permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
 * GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER
 * IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
 * IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

OWLAPI_OPTION(ACCEPT_HTTP_COMPRESSION, "accept-http-compression", OWLAPI_OPTION_BOOLEAN, NULL)
OWLAPI_OPTION(CONNECTION_TIMEOUT, "connection-timeout", OWLAPI_OPTION_INTEGER, NULL)
OWLAPI_OPTION(FOLLOW_REDIRECTS, "follow-redirects", OWLAPI_OPTION_BOOLEAN, NULL)
OWLAPI_OPTION(LOAD_ANNOTATIONS, "load-annotations", OWLAPI_OPTION_BOOLEAN, NULL)
OWLAPI_OPTION(MISSING_IMPORT_HANDLING_STRATEGY, "missing-import-strategy", OWLAPI_OPTION_ENUM, "SILENT", "THROW_EXCEPTION", NULL)
OWLAPI_OPTION(MISSING_ONTOLOGY_HEADER_STRATEGY, "missing-header-strategy", OWLAPI_OPTION_ENUM, "INCLUDE_GRAPH", "IMPORT_GRAPH", NULL)
OWLAPI_OPTION(REPORT_STACK_TRACES, "report-stack-traces", OWLAPI_OPTION_BOOLEAN, NULL)
OWLAPI_OPTION(RETRIES_TO_ATTEMPT, "retries-attempt", OWLAPI_OPTION_INTEGER, NULL)
OWLAPI_OPTION(PARSE_WITH_STRICT_CONFIGURATION, "strict-parse", OWLAPI_OPTION_BOOLEAN, NULL)
OWLAPI_OPTION(TREAT_DUBLINCORE_AS_BUILTIN, "dublin-core-builtin", OWLAPI_OPTION_BOOLEAN, NULL)
OWLAPI_OPTION(PRIORITY_COLLECTION_SORTING, "priority-collection-sorting", OWLAPI_OPTION_ENUM, "ON_SET_INJECTION_ONLY", "NEVER", NULL)
OWLAPI_OPTION(SAVE_IDS, "save-ids", OWLAPI_OPTION_BOOLEAN, NULL)
OWLAPI_OPTION(REMAP_IDS, "remap-ids", OWLAPI_OPTION_BOOLEAN, NULL)
OWLAPI_OPTION(USE_NAMESPACE_ENTITIES, "use-namespace-entities", OWLAPI_OPTION_BOOLEAN, NULL)
OWLAPI_OPTION(INDENTING, "indenting", OWLAPI_OPTION_BOOLEAN, NULL)
OWLAPI_OPTION(INDENT_SIZE, "indent-size", OWLAPI_OPTION_INTEGER, NULL)
OWLAPI_OPTION(LABELS_AS_BANNER, "labels-as-bammer", OWLAPI_OPTION_BOOLEAN, NULL)
OWLAPI_OPTION(BANNERS_ENABLED, "banners-enabled", OWLAPI_OPTION_BOOLEAN, NULL)
OWLAPI_OPTION(ENTITY_EXPANSION_LIMIT, "entity-expansion-limit", OWLAPI_OPTION_INTEGER, NULL)
OWLAPI_OPTION(REPAIR_ILLEGAL_PUNNING, "repair-illegal-punning", OWLAPI_OPTION_BOOLEAN, NULL)
OWLAPI_OPTION(AUTHORIZATION_VALUE, "authorization-value", OWLAPI_OPTION_STRING, NULL)
OWLAPI_OPTION(TRIM_TO_SIZE, "trim-to-size", OWLAPI_OPTION_BOOLEAN, NULL)
OWLAPI_OPTION(SKIP_MODULE_ANNOTATIONS, "skip-module-annotations", OWLAPI_OPTION_BOOLEAN, NULL)
OWLAPI_OPTION(ALLOW_DUPLICATES_IN_CONSTRUCT_SETS, "allow-duplicates", OWLAPI_OPTION_BOOLEAN, NULL)
OWLAPI_OPTION(CACHE_SIZE, "cache-size", OWLAPI_OPTION_INTEGER, NULL)
OWLAPI_OPTION(OUTPUT_NAMED_GRAPH_IRI, "output-named-graph-iri", OWLAPI_OPTION_BOOLEAN, NULL)
